INSERT INTO warehouses (id, name, city, street, post_code)
VALUES (1, 'Byfleet', 'Surrey', '113-115 Oyster Lane', 'KT14 7JZ'),
       (2, 'Bromley ', 'Kent', '12 Farwig Lane', 'BR1 3RB'),
       (3, 'Bow ', 'London', '400 Wick Lane', 'E3 2JG'),
       (4, 'Beckenham ', 'Kent', '1 Croydon Road', 'BR3 4AA'),
       (5, 'Battersea ', 'London', '55 Lombard Road', 'SW11 3RX'),
       (6, 'Barking ', 'London', 'Hertford Road', 'IG11 8BL'),
       (7, 'Balham ', 'London', '7 Weir Road', 'SW12 0LT'),
       (8, 'Croydon ', 'London', '202 - 216 Thornton Road', 'CR0 3EU'),
       (9, 'Chiswick ', 'Middlesex', '961 Great West Road', 'TW8 9FX'),
       (10, 'Camberwell', 'London', '49-65 Southampton Way', 'SE5 7SW'),
       (11, 'Enfield ', 'London', '1 Progress Way', 'EN1 1FT'),
       (12, 'Eltham ', 'London', '400 Westhorne Avenue', 'SE9 5LT'),
       (13, 'Edmonton ', 'London', '8 Advent Way', 'N18 3AF'),
       (14, 'Ealing ', 'London', '399 Uxbridge Road', 'UB1 3EW'),
       (15, 'Dagenham ', 'Barking', '25 Alfreds Way', 'IG11 0AG'),
       (16, 'Ilford ', 'Essex', '374 Eastern Avenue', 'IG2 6NW'),
       (17, 'Hounslow ', 'Middlesex', '179 - 191 Staines Road', 'TW3 3LL'),
       (18, 'Hanger ', 'London', 'Quill Street', 'W5 1DN'),
       (19, 'Gypsy Corner', 'London', '12 Jenner Avenue', 'W3 6EQ'),
       (20, 'Fulham ', 'London', '71 Townmead Road', 'SW6 2ST'),
       (21, 'Finchley North ', 'London', '447 High Road', 'N12 0AF'),
       (22, 'Finchley East  ', 'London', '401 High Road', 'N2 8HS'),
       (23, 'Sheen  ', 'Surrey', '197 Lower Richmond Road', 'TW9 4LN'),
       (24, 'Romford  ', 'Essex', 'Ashton Road', 'RM3 8NF'),
       (25, 'Richmond  ', 'Surrey', 'Lower Mortlake Road', 'TW9 2JX'),
       (26, 'Orpington  ', 'Orpington', 'Cray Avenue', 'BR5 3PX'),
       (27, 'North Kensington  ', 'London', '149 Scrubs Lane', 'NW10 6RH'),
       (28, 'Nine Elms ', 'London', '120 - 170 Stewarts Road', 'SW8 4UB'),
       (29, 'New Malden ', 'New Malden', 'Beverley Way', 'KT3 4PH'),
       (30, 'New Cross ', 'London', '155 Lewisham Way', 'SE14 6QP'),
       (31, 'Merton  ', 'London', '61 Morden Road', 'SW19 3BE'),
       (32, 'Kingston  ', 'Surrey', '163 London Road', 'KT2 6NU'),
       (33, 'Kennington  ', 'London', '289 Kennington Lane', 'SE11 5QY'),
       (34, 'West Norwood  ', 'London', '107 Knights Hill', 'SE27 0SP'),
       (35, 'West Molesey ', 'West Molesey', '36 Central Avenue', 'KT8 2QZ'),
       (36, 'Watford  ', 'Hertfordshire', '1 Ascot Road', 'WD18 8AL'),
       (37, 'Wapping ', 'London', '100 The Highway ', 'E1W 2BX'),
       (38, 'Wandsworth  ', 'London', '100 Garratt Lane', 'SW18 4DJ'),
       (39, 'Twickenham  ', 'Middlesex', '1A Rugby Road ', 'TW1 1DG'),
       (40, 'Tolworth  ', 'Surrey', '225 Hook Rise South', 'KT6 7LD'),
       (41, 'Sutton  ', 'Surrey', '12 Kimpton Park Way', 'SM3 9QS'),
       (42, 'Staples Corner  ', 'London', '1000 North Circular Road', 'NW2 7JP');

