-- DROP TABLE IF EXISTS users,warehouses,user_warehouses,storage_rooms;
--
-- CREATE TABLE IF NOT EXISTS users (
-- id INT AUTO_INCREMENT PRIMARY KEY,
-- first_name VARCHAR(100) NOT NULL,
-- last_name VARCHAR(100) NOT NULL,
-- password VARCHAR(100) NOT NULL,
-- email VARCHAR(255) NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS warehouses (
-- id INT AUTO_INCREMENT PRIMARY KEY,
-- name VARCHAR(100) NOT NULL,
-- city VARCHAR(100) NOT NULL,
-- street_number INT NOT NULL,
-- street VARCHAR(100) NOT NULL,
-- postCode VARCHAR(100) NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS user_warehouses (
-- user_id INT NOT NULL,
-- warehouse_id INT NOT NULL,
-- FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE,
-- FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON UPDATE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS storage_rooms (
-- id INT AUTO_INCREMENT PRIMARY KEY,
-- size DOUBLE NOT NULL,
-- reserved BOOLEAN NOT NULL,
-- startDate DATE,
-- endDate DATE
-- );